site_name: MyDocs
theme:
  name: material
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde